export const SET_USERS = 'SET_USERS'
export const SET_USER = 'SET_USER'
export const SET_IS_SHOW_USER_DETAIL = 'SET_IS_SHOW_USER_DETAIL'
export const SET_IS_LOADING_FETCH_USERS = 'SET_IS_LOADING_FETCH_USERS'